# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProceSIMS_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1567, 928)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QWidget(self.centralwidget)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout.addWidget(self.main_frame)
        self.tabAnalyses_type = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabAnalyses_type.sizePolicy().hasHeightForWidth())
        self.tabAnalyses_type.setSizePolicy(sizePolicy)
        self.tabAnalyses_type.setMinimumSize(QtCore.QSize(330, 0))
        self.tabAnalyses_type.setObjectName("tabAnalyses_type")
        self.tab_Isotopes = QtWidgets.QWidget()
        self.tab_Isotopes.setObjectName("tab_Isotopes")
        self.pushButton_files_iso = QtWidgets.QPushButton(self.tab_Isotopes)
        self.pushButton_files_iso.setGeometry(QtCore.QRect(200, 10, 114, 32))
        self.pushButton_files_iso.setObjectName("pushButton_files_iso")
        self.comboBox_Isotopic_system = QtWidgets.QComboBox(self.tab_Isotopes)
        self.comboBox_Isotopic_system.setGeometry(QtCore.QRect(10, 50, 141, 32))
        self.comboBox_Isotopic_system.setObjectName("comboBox_Isotopic_system")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_Isotopic_system.addItem("")
        self.comboBox_nb_std_iso = QtWidgets.QComboBox(self.tab_Isotopes)
        self.comboBox_nb_std_iso.setGeometry(QtCore.QRect(10, 130, 151, 32))
        self.comboBox_nb_std_iso.setObjectName("comboBox_nb_std_iso")
        self.comboBox_nb_std_iso.addItem("")
        self.comboBox_nb_std_iso.addItem("")
        self.comboBox_nb_std_iso.addItem("")
        self.label_files_iso = QtWidgets.QLabel(self.tab_Isotopes)
        self.label_files_iso.setGeometry(QtCore.QRect(20, 15, 181, 21))
        self.label_files_iso.setObjectName("label_files_iso")
        self.checkBox_drift_iso = QtWidgets.QCheckBox(self.tab_Isotopes)
        self.checkBox_drift_iso.setGeometry(QtCore.QRect(20, 280, 131, 20))
        self.checkBox_drift_iso.setObjectName("checkBox_drift_iso")
        self.comboBox_drift_order_iso = QtWidgets.QComboBox(self.tab_Isotopes)
        self.comboBox_drift_order_iso.setEnabled(False)
        self.comboBox_drift_order_iso.setGeometry(QtCore.QRect(150, 272, 165, 41))
        self.comboBox_drift_order_iso.setObjectName("comboBox_drift_order_iso")
        self.comboBox_drift_order_iso.addItem("")
        self.comboBox_drift_order_iso.addItem("")
        self.comboBox_drift_order_iso.addItem("")
        self.comboBox_drift_order_iso.addItem("")
        self.comboBox_drift_order_iso.addItem("")
        self.comboBox_drift_order_iso.addItem("")
        self.comboBox_drift_order_iso.addItem("")
        self.checkBox_bias_iso = QtWidgets.QCheckBox(self.tab_Isotopes)
        self.checkBox_bias_iso.setGeometry(QtCore.QRect(20, 320, 201, 20))
        self.checkBox_bias_iso.setObjectName("checkBox_bias_iso")
        self.pushButton_plot_iso = QtWidgets.QPushButton(self.tab_Isotopes)
        self.pushButton_plot_iso.setGeometry(QtCore.QRect(30, 360, 241, 32))
        self.pushButton_plot_iso.setObjectName("pushButton_plot_iso")
        self.comboBox_ratio_iso = QtWidgets.QComboBox(self.tab_Isotopes)
        self.comboBox_ratio_iso.setGeometry(QtCore.QRect(222, 89, 94, 32))
        self.comboBox_ratio_iso.setObjectName("comboBox_ratio_iso")
        self.comboBox_ratio_iso.addItem("")
        self.comboBox_ratio_iso.addItem("")
        self.comboBox_ratio_iso.addItem("")
        self.comboBox_ratio_iso.addItem("")
        self.comboBox_ratio_iso.addItem("")
        self.comboBox_ratio_iso.addItem("")
        self.comboBox_ratio_iso.addItem("")
        self.comboBox_ratio_iso.addItem("")
        self.label_ratio_iso = QtWidgets.QLabel(self.tab_Isotopes)
        self.label_ratio_iso.setGeometry(QtCore.QRect(20, 92, 201, 21))
        self.label_ratio_iso.setObjectName("label_ratio_iso")
        self.label_std3_name_iso = QtWidgets.QLabel(self.tab_Isotopes)
        self.label_std3_name_iso.setEnabled(False)
        self.label_std3_name_iso.setGeometry(QtCore.QRect(20, 232, 121, 16))
        self.label_std3_name_iso.setObjectName("label_std3_name_iso")
        self.label_std2_name_iso = QtWidgets.QLabel(self.tab_Isotopes)
        self.label_std2_name_iso.setEnabled(False)
        self.label_std2_name_iso.setGeometry(QtCore.QRect(20, 202, 121, 16))
        self.label_std2_name_iso.setObjectName("label_std2_name_iso")
        self.lineEdit_std2_name_iso = QtWidgets.QLineEdit(self.tab_Isotopes)
        self.lineEdit_std2_name_iso.setEnabled(False)
        self.lineEdit_std2_name_iso.setGeometry(QtCore.QRect(150, 200, 113, 21))
        self.lineEdit_std2_name_iso.setObjectName("lineEdit_std2_name_iso")
        self.label_std1_name_iso = QtWidgets.QLabel(self.tab_Isotopes)
        self.label_std1_name_iso.setGeometry(QtCore.QRect(20, 172, 121, 16))
        self.label_std1_name_iso.setObjectName("label_std1_name_iso")
        self.lineEdit_std3_name_iso = QtWidgets.QLineEdit(self.tab_Isotopes)
        self.lineEdit_std3_name_iso.setEnabled(False)
        self.lineEdit_std3_name_iso.setGeometry(QtCore.QRect(150, 230, 113, 21))
        self.lineEdit_std3_name_iso.setObjectName("lineEdit_std3_name_iso")
        self.lineEdit_std1_name_iso = QtWidgets.QLineEdit(self.tab_Isotopes)
        self.lineEdit_std1_name_iso.setGeometry(QtCore.QRect(150, 170, 113, 21))
        self.lineEdit_std1_name_iso.setObjectName("lineEdit_std1_name_iso")
        self.label_stats_iso = QtWidgets.QLabel(self.tab_Isotopes)
        self.label_stats_iso.setGeometry(QtCore.QRect(30, 420, 271, 391))
        self.label_stats_iso.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_stats_iso.setObjectName("label_stats_iso")
        self.checkBox_comments = QtWidgets.QCheckBox(self.tab_Isotopes)
        self.checkBox_comments.setGeometry(QtCore.QRect(190, 135, 121, 20))
        self.checkBox_comments.setObjectName("checkBox_comments")
        self.tabAnalyses_type.addTab(self.tab_Isotopes, "")
        self.tab_Concentration = QtWidgets.QWidget()
        self.tab_Concentration.setObjectName("tab_Concentration")
        self.pushButton_files_conc = QtWidgets.QPushButton(self.tab_Concentration)
        self.pushButton_files_conc.setGeometry(QtCore.QRect(200, 10, 114, 32))
        self.pushButton_files_conc.setObjectName("pushButton_files_conc")
        self.label_files_conc = QtWidgets.QLabel(self.tab_Concentration)
        self.label_files_conc.setGeometry(QtCore.QRect(20, 15, 181, 21))
        self.label_files_conc.setObjectName("label_files_conc")
        self.comboBox_nb_ratios_conc = QtWidgets.QComboBox(self.tab_Concentration)
        self.comboBox_nb_ratios_conc.setGeometry(QtCore.QRect(10, 50, 211, 32))
        self.comboBox_nb_ratios_conc.setObjectName("comboBox_nb_ratios_conc")
        self.comboBox_nb_ratios_conc.addItem("")
        self.comboBox_nb_ratios_conc.addItem("")
        self.comboBox_nb_ratios_conc.addItem("")
        self.comboBox_nb_ratios_conc.addItem("")
        self.comboBox_nb_std_conc = QtWidgets.QComboBox(self.tab_Concentration)
        self.comboBox_nb_std_conc.setGeometry(QtCore.QRect(10, 90, 151, 32))
        self.comboBox_nb_std_conc.setObjectName("comboBox_nb_std_conc")
        self.comboBox_nb_std_conc.addItem("")
        self.comboBox_nb_std_conc.addItem("")
        self.comboBox_nb_std_conc.addItem("")
        self.checkBox_drift_conc = QtWidgets.QCheckBox(self.tab_Concentration)
        self.checkBox_drift_conc.setGeometry(QtCore.QRect(20, 240, 131, 20))
        self.checkBox_drift_conc.setObjectName("checkBox_drift_conc")
        self.comboBox_drift_order_conc = QtWidgets.QComboBox(self.tab_Concentration)
        self.comboBox_drift_order_conc.setEnabled(False)
        self.comboBox_drift_order_conc.setGeometry(QtCore.QRect(150, 230, 165, 41))
        self.comboBox_drift_order_conc.setObjectName("comboBox_drift_order_conc")
        self.comboBox_drift_order_conc.addItem("")
        self.comboBox_drift_order_conc.addItem("")
        self.comboBox_drift_order_conc.addItem("")
        self.comboBox_drift_order_conc.addItem("")
        self.comboBox_drift_order_conc.addItem("")
        self.comboBox_drift_order_conc.addItem("")
        self.comboBox_drift_order_conc.addItem("")
        self.checkBox_bias_conc = QtWidgets.QCheckBox(self.tab_Concentration)
        self.checkBox_bias_conc.setGeometry(QtCore.QRect(20, 280, 201, 20))
        self.checkBox_bias_conc.setObjectName("checkBox_bias_conc")
        self.pushButton_plot_conc = QtWidgets.QPushButton(self.tab_Concentration)
        self.pushButton_plot_conc.setGeometry(QtCore.QRect(30, 320, 241, 32))
        self.pushButton_plot_conc.setObjectName("pushButton_plot_conc")
        self.label_std1_name_conc = QtWidgets.QLabel(self.tab_Concentration)
        self.label_std1_name_conc.setGeometry(QtCore.QRect(20, 132, 121, 16))
        self.label_std1_name_conc.setObjectName("label_std1_name_conc")
        self.label_std2_name_conc = QtWidgets.QLabel(self.tab_Concentration)
        self.label_std2_name_conc.setEnabled(False)
        self.label_std2_name_conc.setGeometry(QtCore.QRect(20, 162, 121, 16))
        self.label_std2_name_conc.setObjectName("label_std2_name_conc")
        self.label_std3_name_conc = QtWidgets.QLabel(self.tab_Concentration)
        self.label_std3_name_conc.setEnabled(False)
        self.label_std3_name_conc.setGeometry(QtCore.QRect(20, 192, 121, 16))
        self.label_std3_name_conc.setObjectName("label_std3_name_conc")
        self.lineEdit_std3_name_conc = QtWidgets.QLineEdit(self.tab_Concentration)
        self.lineEdit_std3_name_conc.setEnabled(False)
        self.lineEdit_std3_name_conc.setGeometry(QtCore.QRect(150, 190, 113, 21))
        self.lineEdit_std3_name_conc.setObjectName("lineEdit_std3_name_conc")
        self.lineEdit_std2_name_conc = QtWidgets.QLineEdit(self.tab_Concentration)
        self.lineEdit_std2_name_conc.setEnabled(False)
        self.lineEdit_std2_name_conc.setGeometry(QtCore.QRect(150, 160, 113, 21))
        self.lineEdit_std2_name_conc.setObjectName("lineEdit_std2_name_conc")
        self.lineEdit_std1_name_conc = QtWidgets.QLineEdit(self.tab_Concentration)
        self.lineEdit_std1_name_conc.setGeometry(QtCore.QRect(150, 130, 113, 21))
        self.lineEdit_std1_name_conc.setObjectName("lineEdit_std1_name_conc")
        self.label_stats_conc = QtWidgets.QLabel(self.tab_Concentration)
        self.label_stats_conc.setGeometry(QtCore.QRect(30, 370, 271, 441))
        self.label_stats_conc.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_stats_conc.setObjectName("label_stats_conc")
        self.tabAnalyses_type.addTab(self.tab_Concentration, "")
        self.horizontalLayout.addWidget(self.tabAnalyses_type)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1567, 22))
        self.menubar.setObjectName("menubar")
        self.menuProceSIMS = QtWidgets.QMenu(self.menubar)
        self.menuProceSIMS.setObjectName("menuProceSIMS")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFitting = QtWidgets.QMenu(self.menubar)
        self.menuFitting.setObjectName("menuFitting")
        self.menuFigures = QtWidgets.QMenu(self.menubar)
        self.menuFigures.setObjectName("menuFigures")
        self.menuOutput = QtWidgets.QMenu(self.menubar)
        self.menuOutput.setObjectName("menuOutput")
        self.menuMore = QtWidgets.QMenu(self.menubar)
        self.menuMore.setObjectName("menuMore")
        self.menuInput_data = QtWidgets.QMenu(self.menubar)
        self.menuInput_data.setObjectName("menuInput_data")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_ProceSIMS = QtWidgets.QAction(MainWindow)
        self.actionAbout_ProceSIMS.setObjectName("actionAbout_ProceSIMS")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionNew_project = QtWidgets.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionOpen_project = QtWidgets.QAction(MainWindow)
        self.actionOpen_project.setObjectName("actionOpen_project")
        self.actionSave_project = QtWidgets.QAction(MainWindow)
        self.actionSave_project.setObjectName("actionSave_project")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionResiduals = QtWidgets.QAction(MainWindow)
        self.actionResiduals.setObjectName("actionResiduals")
        self.actionAdvanced_statistics = QtWidgets.QAction(MainWindow)
        self.actionAdvanced_statistics.setObjectName("actionAdvanced_statistics")
        self.actionStandards = QtWidgets.QAction(MainWindow)
        self.actionStandards.setObjectName("actionStandards")
        self.actionResiduals_2 = QtWidgets.QAction(MainWindow)
        self.actionResiduals_2.setEnabled(False)
        self.actionResiduals_2.setObjectName("actionResiduals_2")
        self.actionAll_data = QtWidgets.QAction(MainWindow)
        self.actionAll_data.setObjectName("actionAll_data")
        self.actionStandard_data = QtWidgets.QAction(MainWindow)
        self.actionStandard_data.setObjectName("actionStandard_data")
        self.actionSample_data = QtWidgets.QAction(MainWindow)
        self.actionSample_data.setObjectName("actionSample_data")
        self.actionWhole_session = QtWidgets.QAction(MainWindow)
        self.actionWhole_session.setObjectName("actionWhole_session")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOptics_and_primary = QtWidgets.QAction(MainWindow)
        self.actionOptics_and_primary.setObjectName("actionOptics_and_primary")
        self.actionInput_data = QtWidgets.QAction(MainWindow)
        self.actionInput_data.setObjectName("actionInput_data")
        self.actionData = QtWidgets.QAction(MainWindow)
        self.actionData.setObjectName("actionData")
        self.actionStatistics = QtWidgets.QAction(MainWindow)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionDeadtime = QtWidgets.QAction(MainWindow)
        self.actionDeadtime.setEnabled(False)
        self.actionDeadtime.setObjectName("actionDeadtime")
        self.actionBackground = QtWidgets.QAction(MainWindow)
        self.actionBackground.setEnabled(False)
        self.actionBackground.setObjectName("actionBackground")
        self.actionChange_of_cycles = QtWidgets.QAction(MainWindow)
        self.actionChange_of_cycles.setEnabled(False)
        self.actionChange_of_cycles.setObjectName("actionChange_of_cycles")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.menuProceSIMS.addAction(self.actionAbout_ProceSIMS)
        self.menuProceSIMS.addAction(self.actionPreferences)
        self.menuProceSIMS.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionNew_project)
        self.menuFile.addAction(self.actionOpen_project)
        self.menuFile.addAction(self.actionSave_project)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFitting.addAction(self.actionAdvanced_statistics)
        self.menuFitting.addAction(self.actionStatistics)
        self.menuFigures.addAction(self.actionStandards)
        self.menuFigures.addAction(self.actionResiduals_2)
        self.menuFigures.addAction(self.actionAll_data)
        self.menuOutput.addAction(self.actionStandard_data)
        self.menuOutput.addAction(self.actionSample_data)
        self.menuOutput.addAction(self.actionWhole_session)
        self.menuOutput.addAction(self.actionInput_data)
        self.menuMore.addAction(self.actionOptics_and_primary)
        self.menuInput_data.addAction(self.actionData)
        self.menuInput_data.addAction(self.actionDeadtime)
        self.menuInput_data.addAction(self.actionBackground)
        self.menuInput_data.addAction(self.actionChange_of_cycles)
        self.menuInput_data.addAction(self.actionReset)
        self.menubar.addAction(self.menuProceSIMS.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuInput_data.menuAction())
        self.menubar.addAction(self.menuFitting.menuAction())
        self.menubar.addAction(self.menuFigures.menuAction())
        self.menubar.addAction(self.menuOutput.menuAction())
        self.menubar.addAction(self.menuMore.menuAction())

        self.retranslateUi(MainWindow)
        self.tabAnalyses_type.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_files_iso.setText(_translate("MainWindow", "Files"))
        self.comboBox_Isotopic_system.setItemText(0, _translate("MainWindow", "dD"))
        self.comboBox_Isotopic_system.setItemText(1, _translate("MainWindow", "d7Li"))
        self.comboBox_Isotopic_system.setItemText(2, _translate("MainWindow", "d11B"))
        self.comboBox_Isotopic_system.setItemText(3, _translate("MainWindow", "d13C"))
        self.comboBox_Isotopic_system.setItemText(4, _translate("MainWindow", "d18O (VPDB)"))
        self.comboBox_Isotopic_system.setItemText(5, _translate("MainWindow", "d18O (VSMOW)"))
        self.comboBox_Isotopic_system.setItemText(6, _translate("MainWindow", "D17O"))
        self.comboBox_Isotopic_system.setItemText(7, _translate("MainWindow", "d37Cl"))
        self.comboBox_Isotopic_system.setItemText(8, _translate("MainWindow", "Al-Mg (FC-EM)"))
        self.comboBox_Isotopic_system.setItemText(9, _translate("MainWindow", "Al-Mg (EM-EM)"))
        self.comboBox_Isotopic_system.setItemText(10, _translate("MainWindow", "Unspecified"))
        self.comboBox_nb_std_iso.setItemText(0, _translate("MainWindow", "1 standard"))
        self.comboBox_nb_std_iso.setItemText(1, _translate("MainWindow", "2 standards"))
        self.comboBox_nb_std_iso.setItemText(2, _translate("MainWindow", "3 standards"))
        self.label_files_iso.setText(_translate("MainWindow", "Select folder for .asc files :"))
        self.checkBox_drift_iso.setText(_translate("MainWindow", "Drift crorrection"))
        self.comboBox_drift_order_iso.setItemText(0, _translate("MainWindow", "Linear"))
        self.comboBox_drift_order_iso.setItemText(1, _translate("MainWindow", "2nd order polynomial"))
        self.comboBox_drift_order_iso.setItemText(2, _translate("MainWindow", "3rd order polynomial"))
        self.comboBox_drift_order_iso.setItemText(3, _translate("MainWindow", "4th order polynomial"))
        self.comboBox_drift_order_iso.setItemText(4, _translate("MainWindow", "5th order polynomial"))
        self.comboBox_drift_order_iso.setItemText(5, _translate("MainWindow", "6th order polynomial"))
        self.comboBox_drift_order_iso.setItemText(6, _translate("MainWindow", "7th order polynomial"))
        self.checkBox_bias_iso.setText(_translate("MainWindow", "Automatic bias correction"))
        self.pushButton_plot_iso.setText(_translate("MainWindow", "Plot data !"))
        self.comboBox_ratio_iso.setItemText(0, _translate("MainWindow", "1st ratio"))
        self.comboBox_ratio_iso.setItemText(1, _translate("MainWindow", "2nd ratio"))
        self.comboBox_ratio_iso.setItemText(2, _translate("MainWindow", "3rd ratio"))
        self.comboBox_ratio_iso.setItemText(3, _translate("MainWindow", "4th ratio"))
        self.comboBox_ratio_iso.setItemText(4, _translate("MainWindow", "5th ratio"))
        self.comboBox_ratio_iso.setItemText(5, _translate("MainWindow", "6th ratio"))
        self.comboBox_ratio_iso.setItemText(6, _translate("MainWindow", "7th ratio"))
        self.comboBox_ratio_iso.setItemText(7, _translate("MainWindow", "8th ratio"))
        self.label_ratio_iso.setText(_translate("MainWindow", "Which ratio is the isotopic ratio :"))
        self.label_std3_name_iso.setText(_translate("MainWindow", "Standard 3 name :"))
        self.label_std2_name_iso.setText(_translate("MainWindow", "Standard 2 name :"))
        self.label_std1_name_iso.setText(_translate("MainWindow", "Standard 1 name :"))
        self.label_stats_iso.setText(_translate("MainWindow", "Statistics:"))
        self.checkBox_comments.setText(_translate("MainWindow", " Use comments"))
        self.tabAnalyses_type.setTabText(self.tabAnalyses_type.indexOf(self.tab_Isotopes), _translate("MainWindow", "Isotopes"))
        self.pushButton_files_conc.setText(_translate("MainWindow", "Files"))
        self.label_files_conc.setText(_translate("MainWindow", "Select folder for .asc files :"))
        self.comboBox_nb_ratios_conc.setItemText(0, _translate("MainWindow", "1 ratio"))
        self.comboBox_nb_ratios_conc.setItemText(1, _translate("MainWindow", "2 ratios"))
        self.comboBox_nb_ratios_conc.setItemText(2, _translate("MainWindow", "3 ratios"))
        self.comboBox_nb_ratios_conc.setItemText(3, _translate("MainWindow", "4 ratios"))
        self.comboBox_nb_std_conc.setItemText(0, _translate("MainWindow", "1 standard"))
        self.comboBox_nb_std_conc.setItemText(1, _translate("MainWindow", "2 standards"))
        self.comboBox_nb_std_conc.setItemText(2, _translate("MainWindow", "3 standards"))
        self.checkBox_drift_conc.setText(_translate("MainWindow", "Drift crorrection"))
        self.comboBox_drift_order_conc.setItemText(0, _translate("MainWindow", "Linear"))
        self.comboBox_drift_order_conc.setItemText(1, _translate("MainWindow", "2nd order polynomial"))
        self.comboBox_drift_order_conc.setItemText(2, _translate("MainWindow", "3rd order polynomial"))
        self.comboBox_drift_order_conc.setItemText(3, _translate("MainWindow", "4th order polynomial"))
        self.comboBox_drift_order_conc.setItemText(4, _translate("MainWindow", "5th order polynomial"))
        self.comboBox_drift_order_conc.setItemText(5, _translate("MainWindow", "6th order polynomial"))
        self.comboBox_drift_order_conc.setItemText(6, _translate("MainWindow", "7th order polynomial"))
        self.checkBox_bias_conc.setText(_translate("MainWindow", "Automatic bias correction"))
        self.pushButton_plot_conc.setText(_translate("MainWindow", "Plot data !"))
        self.label_std1_name_conc.setText(_translate("MainWindow", "Standard 1 name :"))
        self.label_std2_name_conc.setText(_translate("MainWindow", "Standard 2 name :"))
        self.label_std3_name_conc.setText(_translate("MainWindow", "Standard 3 name :"))
        self.label_stats_conc.setText(_translate("MainWindow", "Statistics:"))
        self.tabAnalyses_type.setTabText(self.tabAnalyses_type.indexOf(self.tab_Concentration), _translate("MainWindow", "Concentrations"))
        self.menuProceSIMS.setTitle(_translate("MainWindow", "ProceSIMS"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFitting.setTitle(_translate("MainWindow", "Fitting"))
        self.menuFigures.setTitle(_translate("MainWindow", "Figures"))
        self.menuOutput.setTitle(_translate("MainWindow", "Output"))
        self.menuMore.setTitle(_translate("MainWindow", "More"))
        self.menuInput_data.setTitle(_translate("MainWindow", "Input data"))
        self.actionAbout_ProceSIMS.setText(_translate("MainWindow", "About ProceSIMS"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionNew_project.setText(_translate("MainWindow", "New project"))
        self.actionOpen_project.setText(_translate("MainWindow", "Open project"))
        self.actionSave_project.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionResiduals.setText(_translate("MainWindow", "Residuals"))
        self.actionAdvanced_statistics.setText(_translate("MainWindow", "Advanced statistics"))
        self.actionStandards.setText(_translate("MainWindow", "Standards"))
        self.actionResiduals_2.setText(_translate("MainWindow", "Residuals"))
        self.actionAll_data.setText(_translate("MainWindow", "All data"))
        self.actionStandard_data.setText(_translate("MainWindow", "Standard data"))
        self.actionSample_data.setText(_translate("MainWindow", "Sample data"))
        self.actionWhole_session.setText(_translate("MainWindow", "Whole session"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionOptics_and_primary.setText(_translate("MainWindow", "Sec. optics and primary"))
        self.actionInput_data.setText(_translate("MainWindow", "Input data"))
        self.actionData.setText(_translate("MainWindow", "Data"))
        self.actionStatistics.setText(_translate("MainWindow", "Statistics"))
        self.actionDeadtime.setText(_translate("MainWindow", "Deadtime"))
        self.actionBackground.setText(_translate("MainWindow", "Background"))
        self.actionChange_of_cycles.setText(_translate("MainWindow", "Change # of cycles"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
